<a href="https://colab.research.google.com/github/Kanak10/pytorch_tutorial/blob/main/01_tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Operation on GPU

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device = torch.device("cuda")

In [ ]:
# creating a new tensor on GPU
torch.rand((2, 3), device=device)

tensor([[0.0875, 0.9345, 0.4117],
        [0.5598, 0.1952, 0.2895]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
a = torch.rand((2, 3))
a

tensor([[0.0086, 0.0643, 0.2293],
        [0.4315, 0.4750, 0.8962]])

In [ ]:
b = a.to(device)

In [ ]:
b + 5

tensor([[5.0086, 5.0643, 5.2293],
        [5.4315, 5.4750, 5.8962]], device='cuda:0')

In [ ]:
import torch
import time

# Define the size of the matrices
size = 10000 # Large size for performance comparison

# create random matrices on GPU
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# MEasure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move the matrices to the GPU
matrix_cup1 = matrix_cup1.to("cuda")
matrix_cpu2 = matrix_cpu2.to("cuda")

# Measure time on GPU
start_time = time.time()
result_cup = torch.matmul(matrix_cup1, matrix_cpu2) # matrix multiplication on GPU
torch.cuda.synchronize() # Ensure all GPU operation are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare result
print("\nSpeedup (CPU time / GPU time):", cpu_time/gpu_time)

Time on CPU: 15.6789 seconds
Time on GPU: 0.7081 seconds

Speedup (CPU time / GPU time): 22.14230461406992
