<a href="https://colab.research.google.com/github/Kanak10/pytorch_tutorial/blob/main/01_tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.11.0+cu130


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [4]:
# using empty
a = torch.empty(2,3)

In [5]:
# Check type
type(a)

torch.Tensor

In [6]:
# using zero
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# Using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2, 3)

tensor([[0.2547, 0.2591, 0.9318],
        [0.2392, 0.6811, 0.5571]])

In [9]:
# use of seed
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2, 3)

In [17]:
# using tensor
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
# other ways

# arange
print("Using arrange ->", torch.arange(0, 10))
print("Using arrange ->", torch.arange(0, 10, 2))

# using linespace
print("using linspace ->", torch.linspace(0, 10, 10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

Using arrange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Using arrange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


##Tensor Shapes

In [23]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
x.shape

torch.Size([2, 3])

In [25]:
torch.empty_like(x)

tensor([[    137081393478560,           400042352,               65536],
        [4687746815133016833,          1092616192,                  97]])

In [27]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [33]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.0420, 0.8548, 0.3101],
        [0.2836, 0.2462, 0.5232]])

##Tensor Data Types

In [28]:
# find data type
x.dtype

torch.int64

In [29]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [30]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [32]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical Operations

### 1. Scalar operation

In [35]:
x = torch.rand(2,2)
x

tensor([[0.0330, 0.8051],
        [0.0917, 0.0962]])

In [36]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0011, 0.6481],
        [0.0084, 0.0093]])

### 2. Element wise operation

In [37]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9415, 0.8114, 0.6297],
        [0.3090, 0.9336, 0.9341]])
tensor([[0.3890, 0.4796, 0.2530],
        [0.2963, 0.0637, 0.2825]])


In [38]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.1634, 0.3318, 0.1236],
        [0.0127, 0.0420, 0.0867]])

In [39]:
c = torch.tensor([1, -2, 3, -4])

In [40]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [41]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [42]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [43]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [44]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [45]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [46]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [47]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[9., 8., 9.],
        [1., 8., 3.]])

In [48]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([26., 12.])

In [49]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([5., 8., 6.])

In [50]:
# median
torch.median(e)

tensor(8.)

In [51]:
# max and min
torch.max(e)
torch.min(e)

tensor(1.)

In [52]:
# product
torch.prod(e)

tensor(15552.)

In [53]:
# standard deviation
torch.std(e)

tensor(3.4448)

In [54]:
# variance
torch.var(e)

tensor(11.8667)

In [55]:
# argmax
torch.argmax(e)

tensor(0)

In [56]:
# argmin
torch.argmin(e)

tensor(3)

### 4. Matrix operations

In [57]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[7, 1, 1],
        [8, 3, 4]])
tensor([[0, 6],
        [4, 6],
        [8, 0]])


In [58]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[12, 48],
        [44, 66]])

In [59]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [60]:
# transpose
torch.transpose(f, 0, 1)

tensor([[7, 8],
        [1, 3],
        [1, 4]])

In [61]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[8., 4., 3.],
        [6., 7., 2.],
        [3., 3., 4.]])

In [62]:
# determinant
torch.det(h)

tensor(95.)

In [63]:
# inverse
torch.inverse(h)

tensor([[ 0.2316, -0.0737, -0.1368],
        [-0.1895,  0.2421,  0.0211],
        [-0.0316, -0.1263,  0.3368]])

### 5. Comparison operations

In [64]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 4, 2],
        [0, 8, 7]])
tensor([[7, 6, 3],
        [2, 7, 1]])


In [70]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j
# less than equal to
i <= j

tensor([[ True,  True,  True],
        [ True, False, False]])

### 6. Special functions

In [66]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[1., 2., 2.],
        [5., 0., 5.]])

In [67]:
# log
torch.log(k)

tensor([[0.0000, 0.6931, 0.6931],
        [1.6094,   -inf, 1.6094]])

In [68]:
# exp
torch.exp(k)

tensor([[  2.7183,   7.3891,   7.3891],
        [148.4132,   1.0000, 148.4132]])

In [71]:
# sqrt
torch.sqrt(k)

tensor([[1.0000, 1.4142, 1.4142],
        [2.2361, 0.0000, 2.2361]])

In [72]:
# sigmoid
torch.sigmoid(k)

tensor([[0.7311, 0.8808, 0.8808],
        [0.9933, 0.5000, 0.9933]])

In [73]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.0180, 0.8808, 0.0474],
        [0.9820, 0.1192, 0.9526]])

In [74]:
# relu
torch.relu(k)

tensor([[1., 2., 2.],
        [5., 0., 5.]])

## Inplace Operations

In [75]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2660, 0.3715, 0.6096],
        [0.5115, 0.0678, 0.5038]])
tensor([[0.7779, 0.2659, 0.3932],
        [0.7483, 0.7985, 0.4626]])


In [76]:
m.add_(n)

tensor([[1.0439, 0.6374, 1.0028],
        [1.2597, 0.8663, 0.9664]])

In [77]:
m

tensor([[1.0439, 0.6374, 1.0028],
        [1.2597, 0.8663, 0.9664]])

In [78]:
n

tensor([[0.7779, 0.2659, 0.3932],
        [0.7483, 0.7985, 0.4626]])

In [79]:
torch.relu(m)

tensor([[1.0439, 0.6374, 1.0028],
        [1.2597, 0.8663, 0.9664]])

In [80]:
m.relu_()

tensor([[1.0439, 0.6374, 1.0028],
        [1.2597, 0.8663, 0.9664]])

In [81]:
m

tensor([[1.0439, 0.6374, 1.0028],
        [1.2597, 0.8663, 0.9664]])

## Copying a Tensor

In [82]:
a = torch.rand(2,3)
a

tensor([[0.9414, 0.5752, 0.8881],
        [0.7989, 0.9514, 0.0141]])

In [83]:
b = a

In [84]:
b

tensor([[0.9414, 0.5752, 0.8881],
        [0.7989, 0.9514, 0.0141]])

In [85]:
a[0][0] = 0

In [88]:
a

tensor([[0.0000, 0.5752, 0.8881],
        [0.7989, 0.9514, 0.0141]])

In [90]:
b

tensor([[0.0000, 0.5752, 0.8881],
        [0.7989, 0.9514, 0.0141]])

In [91]:
id(a)

137075608045280

In [92]:
id(b)

137075608045280

In [93]:
b = a.clone()

In [94]:
a

tensor([[0.0000, 0.5752, 0.8881],
        [0.7989, 0.9514, 0.0141]])

In [95]:
b

tensor([[0.0000, 0.5752, 0.8881],
        [0.7989, 0.9514, 0.0141]])

In [96]:
a[0][0] = 10

In [97]:
a

tensor([[10.0000,  0.5752,  0.8881],
        [ 0.7989,  0.9514,  0.0141]])

In [98]:
b

tensor([[0.0000, 0.5752, 0.8881],
        [0.7989, 0.9514, 0.0141]])

In [99]:
id(a)

137075608045280

In [100]:
id(b)

137075263815296

# Tensor Operation on GPU

In [101]:
import torch
torch.cuda.is_available()

True

In [102]:
device = torch.device("cuda")

In [103]:
# creating a new tensor on GPU
torch.rand((2, 3), device=device)

tensor([[0.8344, 0.7001, 0.5361],
        [0.8883, 0.0220, 0.7938]], device='cuda:0')

In [104]:
# moving an existing tensor to GPU
a = torch.rand((2, 3))
a

tensor([[0.8903, 0.1649, 0.3162],
        [0.1331, 0.6763, 0.4254]])

In [105]:
b = a.to(device)

In [106]:
b + 5

tensor([[5.8903, 5.1649, 5.3162],
        [5.1331, 5.6763, 5.4254]], device='cuda:0')

In [108]:
import torch
import time

# Define the size of the matrices
size = 10000 # Large size for performance comparison

# create random matrices on GPU
matrix_cpu1 = torch.rand(size, size)
matrix_cpu2 = torch.rand(size, size)

# MEasure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) # matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move the matrices to the GPU
matrix_cpu1 = matrix_cpu1.to("cuda")
matrix_cpu2 = matrix_cpu2.to("cuda")

# Measure time on GPU
start_time = time.time()
result_cup = torch.matmul(matrix_cpu1, matrix_cpu2) # matrix multiplication on GPU
torch.cuda.synchronize() # Ensure all GPU operation are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare result
print("\nSpeedup (CPU time / GPU time):", cpu_time/gpu_time)

Time on CPU: 19.0930 seconds
Time on GPU: 0.6719 seconds

Speedup (CPU time / GPU time): 28.417958714098752


## Reshaping Tensors

In [109]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [110]:
# reshape
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [111]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [113]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.7335, 0.7166, 0.4271, 0.8363],
         [0.6585, 0.7211, 0.7063, 0.0397],
         [0.0140, 0.8291, 0.4812, 0.9135]],

        [[0.3784, 0.3297, 0.0069, 0.2086],
         [0.2247, 0.6386, 0.0521, 0.7844],
         [0.5886, 0.1422, 0.4180, 0.5726]]])

In [114]:
# permute
b.permute(2, 0, 1)

tensor([[[0.7335, 0.6585, 0.0140],
         [0.3784, 0.2247, 0.5886]],

        [[0.7166, 0.7211, 0.8291],
         [0.3297, 0.6386, 0.1422]],

        [[0.4271, 0.7063, 0.4812],
         [0.0069, 0.0521, 0.4180]],

        [[0.8363, 0.0397, 0.9135],
         [0.2086, 0.7844, 0.5726]]])

In [115]:
# unsqueeze
c = torch.rand(226, 226, 3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [121]:
# sequeeze
d = torch.rand(1, 20)
d.squeeze(0)

tensor([0.1692, 0.6346, 0.5021, 0.3892, 0.2128, 0.7612, 0.8893, 0.0477, 0.6056,
        0.0987, 0.0995, 0.8745, 0.5727, 0.8085, 0.8438, 0.8734, 0.1312, 0.8906,
        0.0423, 0.6084])

## NumPy and PyTorch

In [123]:
import numpy as np

In [125]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [126]:
b = a.numpy()
b

array([1, 2, 3])

In [127]:
type(b)

numpy.ndarray

In [128]:
c = np.array([1, 2, 3])

In [129]:
torch.from_numpy(c)

tensor([1, 2, 3])