<a href="https://colab.research.google.com/github/Kanak10/pytorch_tutorial/blob/main/04_pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5991],
        [0.6766],
        [0.6379],
        [0.6681],
        [0.6039],
        [0.5746],
        [0.6459],
        [0.5474],
        [0.6871],
        [0.6918]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.3090,  0.3427,  0.3515,  0.2545, -0.0142]], requires_grad=True)

In [ ]:
# show model bias
model.linear.bias

Parameter containing:
tensor([0.2134], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Complex Neural Network

In [ ]:
# create model class
import torch
import torch.nn as nn

class ComplexModel(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:
# create dataset
features = torch.rand(10, 5)

# create model
complex_model = ComplexModel(features.shape[1])

# call model for forward pass
# complex_model.forward(features)
complex_model(features)

tensor([[0.5549],
        [0.5552],
        [0.5544],
        [0.5579],
        [0.5526],
        [0.5542],
        [0.5511],
        [0.5511],
        [0.5611],
        [0.5525]], grad_fn=<SigmoidBackward0>)

In [ ]:
complex_model.linear1.weight, complex_model.linear2.weight

(Parameter containing:
 tensor([[ 0.4262, -0.2047, -0.4022, -0.2329,  0.1549],
         [-0.1339, -0.1537, -0.3621,  0.0564, -0.1081],
         [ 0.1316, -0.3878, -0.2560, -0.0608,  0.3603]], requires_grad=True),
 Parameter containing:
 tensor([[0.1082, 0.0672, 0.0822]], requires_grad=True))

In [ ]:
complex_model.linear1.bias, complex_model.linear2.bias

(Parameter containing:
 tensor([ 0.2880, -0.1924, -0.3263], requires_grad=True),
 Parameter containing:
 tensor([0.2052], requires_grad=True))

In [ ]:
summary(complex_model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
ComplexModel                             [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## Sequantial Container

In [ ]:
# create model class
import torch
import torch.nn as nn

class SequentialContainerModel(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3, 1),
      nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)

    return out

In [ ]:
# create dataset
features = torch.rand(10, 5)

# create model
sequential_container_model = SequentialContainerModel(features.shape[1])

# call model for forward pass
# sequential_container_model.forward(features)
sequential_container_model(features)

tensor([[0.5999],
        [0.5938],
        [0.6000],
        [0.5933],
        [0.5926],
        [0.5920],
        [0.5886],
        [0.5916],
        [0.5996],
        [0.5958]], grad_fn=<SigmoidBackward0>)